import React from "react";
import type {Metadata} from "next";
import {Noto_Sans} from "next/font/google";
import Navbar from "@/components/Navbar";
import Link from "next/link";
import Image from "next/image";
import LeftSidebar from "@/components/LeftSidebar";

const inter = Noto_Sans({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function DashboardLayout({
                                            children,
                                        }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={"h-screen flex"}>
            {/*Left Sidebar*/}
            <div className="w-[14%] md:w-[8%] lg:w-[16%] xl:w-[14%] p-4">
                <Link href={"/"} className="flex items-center justify-center lg:justify-start gap-2" >
                    <Image src={"/logo.png"} alt={"Logo"} height={32} width={32}/>
                    <span className="hidden lg:block font-bold">EduManage</span>
                </Link>
                <LeftSidebar />
            </div>
            {/*Right Sidebar*/}
            <div className="w-[86%] md:w-[92%] lg:w-[84%] xl:w-[86%] bg-[#F7F8FA] overflow-scroll flex flex-col">
                <Navbar/>
                {children}
            </div>
        </div>
    );
}
